development:
  adapter: postgresql
  encoding: UTF8
  database: jsonapis_development
  host: localhost
  pool: 5

test: &test
  adapter: postgresql
  encoding: UTF8
  database: jsonapis_test
  host: localhost
  pool: 5
  min_messages: WARNING
